### ISSUE TITLE
Heroku Crashed

### ISSUE THREAD

**Issue by antoninlanglade** [convertelligence/heroku-buildpack-google-cloud#1]
Hi,

I tried your buildpack and this is the result :

![image](https://user-images.githubusercontent.com/1774288/43129122-fc4a83ba-8f33-11e8-91da-401cbaa9e127.png)

I added the two env vars into my project :

![image](https://user-images.githubusercontent.com/1774288/43129141-0983b1d2-8f34-11e8-82b8-0db098ec82d0.png)

Do you have any idea of what's going wrong ?

Thx

**Comment by petterhh** [comment]
Hi @antoninlanglade!

It seems like you haven't added the [node buildpack](https://github.com/heroku/heroku-buildpack-nodejs) to your app, which has nothing to do with this Google Cloud buildpack! Adding the node buildpack should do the trick.

**Comment by antoninlanglade** [comment]
Thanks man.
